services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\:
        resource: '../../src/Domain/*/Dictionary'
        tags: ['knp_dictionary.dictionary']
