services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\:
        resource: '../../src/Domain/*/Dictionary'
        tags: ['knp_dictionary.dictionary']

    App\Domain\AIPD\Dictionary\ReponseMesureProtectionDictionary:
        arguments: ['@aipd.model.analyse_impact']


