services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Knp\DictionaryBundle\Dictionary\DictionaryRegistry: "@knp_dictionary.dictionary.dictionary_registry"

    App\Domain\:
        resource: '../../src/Domain/*/Dictionary'
        tags: ['knp_dictionary.dictionary']
