services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Application\Symfony\EventSubscriber\:
        resource: '../../src/Application/Symfony/EventSubscriber'
        tags:
            - { name: 'doctrine.event_subscriber' }

    App\Domain\:
        resource: '../../src/Domain/*/Symfony/EventSubscriber'
        tags:
            - { name: 'doctrine.event_subscriber' }

    App\Domain\User\Symfony\EventSubscriber\DefinePasswordSubscriber:
        tags:
            - { name: 'doctrine.event_subscriber', priority: 2 }
