services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Domain\:
        resource: '../../src/Domain/*/Generator'

    App\Domain\Reporting\Generator\Word\ContractorGenerator:
        arguments:
            $defaultReferent: "%env(APP_DEFAULT_REFERENT)%"

    App\Domain\Reporting\Generator\Word\TreatmentGenerator:
        arguments:
            $defaultReferent: "%env(APP_DEFAULT_REFERENT)%"

    App\Domain\Reporting\Handler\WordHandler:
        arguments:
            $dpo: { civility: '%env(APP_DPO_CIVILITY)%', firstName: '%env(APP_DPO_FIRST_NAME)%', lastName: '%env(APP_DPO_LAST_NAME)%', company: '%env(APP_DPO_COMPANY)%', job: '%env(APP_DPO_JOB)%', mail: '%env(APP_DPO_MAIL)%', phoneNumber: '%env(APP_DPO_PHONE_NUMBER)%' }
