parameters:
    app.version: 1.4.1

framework:
    secret: '%env(APP_SECRET)%'
    default_locale: '%locale%'
    #csrf_protection: true
    #http_method_override: true

    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
        cookie_lifetime: 14400 # 4 hours in seconds
        gc_maxlifetime: 5400 # 1.5hours in seconds

    #esi: true
    #fragments: true
    php_errors:
        log: true

    validation:
        mapping:
            paths:
                - '%kernel.project_dir%/config/domain/registry/validation'
                - '%kernel.project_dir%/config/domain/user/validation'
