knpu_oauth2_client:
    clients:
        keycloak:
            type: keycloak
            # add and set these environment variables in your .env files
            client_id: '%env(OAUTH_CLIENT_ID)%'
            client_secret: '%env(OAUTH_CLIENT_SECRET)%'
            # Keycloak server URL
            auth_server_url: '%env(OAUTH_URL)%'
            # Keycloak realm
            realm: '%env(OAUTH_REALM)%'
            # a route name you'll create
            redirect_route: oauth_check
            redirect_params:
                service: keycloak

#    add other oauth2 client here @see https://github.com/knpuniversity/oauth2-client-bundle
