lexik_jwt_authentication:
    secret_key:       '%env(resolve:JWT_PRIVATE_KEY_PATH)%' # required for token creation
    public_key:       '%env(resolve:JWT_PUBLIC_KEY_PATH)%'  # required for token verification
    #secret_key:       '%kernel.project_dir%/config/jwt/private.pem'
    #public_key:       '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase:      '%env(JWT_PASSPHRASE)%' # required for token creation, usage of an environment variable is recommended
    token_ttl:        3600