security:
    encoders:
        App\Domain\User\Model\User:
            algorithm: auto
    providers:
        user_provider:
            entity:
                class: App\Domain\User\Model\User
                property: email

    role_hierarchy:
        ROLE_USER: [ROLE_PREVIEW]
        ROLE_REFERENT: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN: [ROLE_REFERENT]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                login_path: /connexion
                check_path: /connexion
            logout:
                path: /deconnexion
                target: /
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 604800 # 1 week in seconds
            anonymous: ~
            provider: user_provider
            user_checker: App\Domain\User\Symfony\Security\Checker\UserChecker
            switch_user: true

    access_control:
        # Authentication routes
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/deconnexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mot-de-passe-oublie, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reinitialisation-de-mot-de-passe, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/publique, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # Referent routes
        - { path: ^/collectivites/liste, roles: ROLE_REFERENT }
        - { path: ^/collectivites/visualiser/.+$, roles: ROLE_REFERENT }
        - { path: ^/collectivites/datatables, roles: ROLE_REFERENT }
        - { path: ^/utilisateurs/liste, roles: ROLE_REFERENT }
        - { path: ^/utilisateurs/datatables, roles: ROLE_REFERENT }
        # Admin routes
        - { path: ^/collectivites, roles: ROLE_ADMIN }
        - { path: ^/utilisateurs, roles: ROLE_ADMIN }
        - { path: ^/journalisation, roles: ROLE_ADMIN }
        - { path: ^/traitements/configuration, roles: ROLE_ADMIN }
        # Manager routes
        - { path: ^/.+/creer$, roles: ROLE_USER }
        - { path: ^/.+/creer/.+$, roles: ROLE_USER }
        - { path: ^/.+/editer/.+$, roles: ROLE_USER }
        - { path: ^/.+/supprimer/.+$, roles: ROLE_USER }
        - { path: ^/.+/supprimer/.+/confirmation$, roles: ROLE_USER }
        # Others
        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }
