variables:
    DOCKER_DRIVER: overlay2
    DOCKER_IMAGE_PHP: gitlab.adullact.net:4567/soluris/madis/php:1.1
    DOCKER_IMAGE_NGINX: gitlab.adullact.net:4567/soluris/madis/nginx:1.0
    DOCKER_TLS_CERTDIR: ""

stages:
    - cache
    - tests
    - quality-assurance
    - quality-assurance-report

.job-base-template: &job-base-defintion
    image: mykiwi/docker
    services:
        - docker:19.03-dind

.vendor-install-template: &vendor-install-defintion
    before_script:
        - docker login --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_REGISTRY
        # re-install vendors to prevent from ci cache failure
        - docker run --rm --env-file=./.env.dist --env-file=.env.test -v ${PWD}:/var/www/gestion-rgpd $DOCKER_IMAGE_PHP composer install --prefer-dist --no-interaction --optimize-autoloader --no-scripts

.cache-pull-template: &cache-pull-defintion
    cache:
        key: "$CI_PROJECT_PATH-php"
        paths:
            - vendor
        policy: pull

create_cache:
    image: ${DOCKER_IMAGE_PHP}
    script:
        - composer install --prefer-dist --no-interaction --optimize-autoloader --no-scripts
    cache:
        key: "$CI_PROJECT_PATH-php"
        paths:
            - vendor
    stage: cache
    except:
        - master

unit_tests:
    <<: *job-base-defintion
    <<: *vendor-install-defintion
    <<: *cache-pull-defintion
    script:
        - sh docker-service unitTests
# TODO : Fix make commnd since mykiwi/paudit does not have composer installed (in order to use simple-phpunit)
#        - make tu-report
    coverage: '/^\s*Lines:\s*\d+.\d+\%/'
    artifacts:
        paths:
            - var/artefacts/coverage/
        expire_in: 1 month
    stage: tests
    except:
        - master

# TODO validate doctrine migrations and schema

check-security:
    <<: *job-base-defintion
    <<: *vendor-install-defintion
    <<: *cache-pull-defintion
    script:
        - sh docker-service securityCheck
    stage: quality-assurance
    except:
        - master

phpstan:
    <<: *job-base-defintion
    <<: *vendor-install-defintion
    <<: *cache-pull-defintion
    script:
        - make phpstan
    stage: quality-assurance
    except:
        - master

lint:
    <<: *job-base-defintion
    <<: *vendor-install-defintion
    <<: *cache-pull-defintion
    script:
        - cp -f .env.dist .env
        - make lint
    stage: quality-assurance
    except:
        - master

phpmd:
    <<: *job-base-defintion
    script:
        - make phpmd
    artifacts:
        paths:
            - var/artefacts/phpmd
        expire_in: 1 month
    stage: quality-assurance
    only:
        - develop

php-cs-fixer:
    <<: *job-base-defintion
    script:
        - make php-cs-fixer
    stage: quality-assurance
    except:
        - master

phpmetrics:
    <<: *job-base-defintion
    script:
        - make phpmetrics
    artifacts:
        paths:
            - var/artefacts/phpmetrics
        expire_in: 1 month
    stage: quality-assurance
    only:
        - develop

pages:
    <<: *job-base-defintion
    script:
        - export
        - rm -rf public/*
        - cp .gitlab-pages.html var/artefacts/index.html
        - sed -i "s|PLACEHOLDER_PROJECT_PATH|${CI_PROJECT_PATH}|g" var/artefacts/index.html
        - sed -i "s|PLACEHOLDER_PROJECT_NAME|${CI_PROJECT_NAME}|g" var/artefacts/index.html
        - sed -i "s|PLACEHOLDER_GIT_COMMIT_SHA|${CI_COMMIT_SHA}|g" var/artefacts/index.html
        - mv var/artefacts/* public/
    artifacts:
        paths:
            - public
        expire_in: 1 month
    stage: quality-assurance-report
    only:
        - develop
