_domain_maturity:
    resource: ../domain/maturity/routes/_index.yaml

_domain_page:
    resource: ../domain/page/routes/_index.yaml

_domain_registry:
    resource: ../domain/registry/routes/_index.yaml

_domain_reporting:
    resource: ../domain/reporting/routes/_index.yaml

_domain_user:
    resource: ../domain/user/routes/_index.yaml
