_registry_contractor:
    resource: 'contractor.yaml'
    prefix:   '/sous-traitants'

_registry_mesurement:
    resource: 'mesurement.yaml'
    prefix:   '/mesures'

_registry_treatment:
    resource: 'treatment.yaml'
    prefix:   '/traitements'
