_registry_contractor:
    resource: 'contractor.yaml'
    prefix:   '/sous-traitants'

_registry_mesurement:
    resource: 'mesurement.yaml'
    prefix:   '/actions-de-protection'

_registry_proof:
    resource: 'proof.yaml'
    prefix:   '/preuves'

_registry_request:
    resource: 'request.yaml'
    prefix:   '/demandes-des-personnes-concernees'

_registry_treatment:
    resource: 'treatment.yaml'
    prefix:   '/traitements'

_registry_violation:
    resource: 'violation.yaml'
    prefix:   '/violations'
