_registry_contractor:
    resource: 'contractor.yaml'
    prefix:   '/sous-traitants'

_registry_mesurement:
    resource: 'mesurement.yaml'
    prefix:   '/actions-de-protection'

_registry_proof:
    resource: 'proof.yaml'
    prefix:   '/preuves'

_registry_treatment:
    resource: 'treatment.yaml'
    prefix:   '/traitements'
