registry_conformite_organisation_list:
  path: '/liste'
  methods: ['GET']
  controller: 'App\Domain\Registry\Controller\ConformiteOrganisationController::listAction'

registry_conformite_organisation_create:
  path: '/creer'
  methods: ['GET', 'POST']
  controller: 'App\Domain\Registry\Controller\ConformiteOrganisationController:createAction'

