registry_treatment_list:
    path: '/liste'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\TreatmentController:listAction'

registry_treatment_create:
    path: '/creer'
    methods: ['GET', 'POST']
    controller: 'App\Domain\Registry\Controller\TreatmentController:createAction'

registry_treatment_edit:
    path: '/editer/{id}'
    methods: ['GET', 'POST']
    controller: 'App\Domain\Registry\Controller\TreatmentController:editAction'

registry_treatment_show:
    path: '/visualiser/{id}'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\TreatmentController:showAction'

registry_treatment_report:
    path: '/bilan'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\TreatmentController:reportAction'

registry_treatment_delete:
    path: '/supprimer/{id}'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\TreatmentController:deleteAction'

registry_treatment_delete_confirm:
    path: '/supprimer/{id}/confirmation'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\TreatmentController:deleteConfirmationAction'

api_registry_treatment_collectivity:
    path: '/api/collectivite/{collectivityId}'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\TreatmentController:apiGetTreatmentsByCollectivity'

registry_treatment_pdf:
    path: '/pdf/{id}'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\TreatmentController:pdfAction'
