registry_violation_list:
    path: '/liste'
    methods: ['GET']
    defaults:
        _controller: 'App\Domain\Registry\Controller\ViolationController:listAction'

registry_violation_create:
    path: '/creer'
    methods: ['GET', 'POST']
    defaults:
        _controller: 'App\Domain\Registry\Controller\ViolationController:createAction'

registry_violation_edit:
    path: '/editer/{id}'
    methods: ['GET', 'POST']
    defaults:
        _controller: 'App\Domain\Registry\Controller\ViolationController:editAction'

registry_violation_show:
    path: '/visualiser/{id}'
    methods: ['GET']
    defaults:
        _controller: 'App\Domain\Registry\Controller\ViolationController:showAction'

registry_violation_report:
    path: '/bilan'
    methods: ['GET']
    defaults:
        _controller: 'App\Domain\Registry\Controller\ViolationController:reportAction'

registry_violation_delete:
    path: '/archiver/{id}'
    methods: ['GET']
    defaults:
        _controller: 'App\Domain\Registry\Controller\ViolationController:deleteAction'

registry_violation_delete_confirm:
    path: '/archiver/{id}/confirmation'
    methods: ['GET']
    defaults:
        _controller: 'App\Domain\Registry\Controller\ViolationController:deleteConfirmationAction'
