App\Domain\Registry\Model\Request:
    attributes:
        normalization_context:
            groups: [ 'request_read' ]
    collectionOperations: ~
    itemOperations:
        get: ~ 
        put: ~ 