App\Domain\User\Model\Embeddable\Contact:
    properties:
        civility:
            - NotBlank:
                message: 'user_contact.civility.not_blank'
                groups: ['collectivity_legal_manager', 'collectivity_referent']
            - Knp\DictionaryBundle\Validator\Constraints\Dictionary:
                name: 'user_contact_civility'
                groups: ['default']
        firstName:
            - NotBlank:
                message: 'user_contact.first_name.not_blank'
                groups: ['collectivity_legal_manager', 'collectivity_referent']
            - Length:
                max: 255
                groups: ['default']
        job:
            - NotBlank:
                message: 'user_contact.job.not_blank'
                groups: ['collectivity_legal_manager', 'collectivity_referent']
            - Length:
                max: 255
                groups: ['default']
        lastName:
            - NotBlank:
                message: 'user_contact.last_name.not_blank'
                groups: ['collectivity_legal_manager', 'collectivity_referent']
            - Length:
                max: 255
                groups: ['default']
        mail:
            - NotBlank:
                message: 'user_contact.mail.not_blank'
                groups: ['collectivity_legal_manager', 'collectivity_referent']
            - Email:
                message: 'user_contact.mail.email'
                groups: ['default']
            - Length:
                max: 255
                groups: ['default']
        phoneNumber:
            - NotBlank:
                message: 'user_contact.phone_number.not_blank'
                groups: ['collectivity_legal_manager', 'collectivity_referent']
            - Regex:
                  pattern: '/^0[1-9][0-9]{8}$/'
                  message: 'user_contact.phone_number.regex'
                  groups: ['default']
