App\Domain\User\Model\User:

    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['email']
            groups: ['default']

    properties:
        firstName:
            - NotBlank:
                message: 'user_user.first_name.not_blank'
                groups: ['default']
        lastName:
            - NotBlank:
                message: 'user_user.last_name.not_blank'
                groups: ['default']
        email:
            - Email:
                message: 'user_user.email.email'
                groups: ['default']
            - NotBlank:
                message: 'user_user.email.not_blank'
                groups: ['default']
        roles:
            - Count:
                min: 1
                minMessage: 'user_user.roles.min_count'
                groups: ['default']
            - Count:
                max: 1
                minMessage: 'user_user.roles.max_count'
                groups: ['default']
        plainPassword:
            - Expression:
                expression: "this.getPassword() or (this.getPlainPassword() and !this.getPassword())"
                message: 'user_user.plain_password.expression'
                groups: ['default']
            - Rollerworks\Component\PasswordStrength\Validator\Constraints\PasswordRequirements:
                minLength: 14
                requireCaseDiff: true
                requireLetters: true
                requireNumbers: true
                requireSpecialCharacter: true
                groups: ['default']
