App\Domain\User\Model\User:
    properties:
        firstName:
            - NotBlank:
                message: 'user_user.first_name.not_blank'
                groups: ['default']
        lastName:
            - NotBlank:
                message: 'user_user.last_name.not_blank'
                groups: ['default']
        email:
            - Email:
                message: 'user_user.email.email'
                groups: ['default']
            - NotBlank:
                message: 'user_user.email.not_blank'
                groups: ['default']
        roles:
            - Count:
                min: 1
                minMessage: 'user_user.roles.min_count'
                groups: ['default']
            - Count:
                max: 1
                minMessage: 'user_user.roles.max_count'
                groups: ['default']
