App\Domain\User\Model\User:

    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['email']
            groups: ['default']

    properties:
        firstName:
            - NotBlank:
                message: 'user_user.first_name.not_blank'
                groups: ['default']
            - Length:
                max: 255
                groups: ['default']
        lastName:
            - NotBlank:
                message: 'user_user.last_name.not_blank'
                groups: ['default']
            - Length:
                max: 255
                groups: ['default']
        email:
            - Email:
                message: 'user_user.email.email'
                groups: ['default']
            - NotBlank:
                message: 'user_user.email.not_blank'
                groups: ['default']
            - Length:
                max: 255
                groups: ['default']
        roles:
            - Count:
                min: 1
                minMessage: 'user_user.roles.min_count'
                groups: ['default']
            - Count:
                max: 1
                minMessage: 'user_user.roles.max_count'
                groups: ['default']
        plainPassword:
            - App\Domain\User\Validator\Constraints\CustomPassword:
                groups: ['default']
            - Length:
                max: 255
                groups: ['default']
