services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            string $lateRequestDelayDays: '%APP_REQUEST_NOTIFICATION_DELAY_DAYS%'


    App\Infrastructure\ORM\Registry\Repository\:
        resource: '../../../../src/Infrastructure/ORM/Registry/Repository'

    App\Domain\Registry\Repository\ConformiteTraitement\ConformiteTraitement: '@App\Infrastructure\ORM\Registry\Repository\ConformiteTraitement\ConformiteTraitement'
    App\Domain\Registry\Repository\ConformiteTraitement\Question: '@App\Infrastructure\ORM\Registry\Repository\ConformiteTraitement\Question'
    App\Domain\Registry\Repository\Contractor: '@App\Infrastructure\ORM\Registry\Repository\Contractor'
    App\Domain\Registry\Repository\Mesurement: '@App\Infrastructure\ORM\Registry\Repository\Mesurement'
    App\Domain\Registry\Repository\Proof: '@App\Infrastructure\ORM\Registry\Repository\Proof'
    App\Domain\Registry\Repository\ConformiteOrganisation\Evaluation: '@App\Infrastructure\ORM\Registry\Repository\ConformiteOrganisation\Evaluation'
    App\Domain\Registry\Repository\ConformiteOrganisation\Question: '@App\Infrastructure\ORM\Registry\Repository\ConformiteOrganisation\Question'
    App\Domain\Registry\Repository\ConformiteOrganisation\Processus: '@App\Infrastructure\ORM\Registry\Repository\ConformiteOrganisation\Processus'
    App\Domain\Registry\Repository\ConformiteOrganisation\Conformite: '@App\Infrastructure\ORM\Registry\Repository\ConformiteOrganisation\Conformite'
    App\Domain\Registry\Repository\Request: '@App\Infrastructure\ORM\Registry\Repository\Request'
    App\Domain\Registry\Repository\Treatment: '@App\Infrastructure\ORM\Registry\Repository\Treatment'
    App\Domain\Registry\Repository\Violation: '@App\Infrastructure\ORM\Registry\Repository\Violation'
