services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Infrastructure\ORM\Registry\Repository\:
        resource: '../../../../src/Infrastructure/ORM/Registry/Repository'

    App\Domain\Registry\Repository\Contractor: '@App\Infrastructure\ORM\Registry\Repository\Contractor'
    App\Domain\Registry\Repository\Mesurement: '@App\Infrastructure\ORM\Registry\Repository\Mesurement'
    App\Domain\Registry\Repository\Treatment: '@App\Infrastructure\ORM\Registry\Repository\Treatment'
