maturity_survey_list:
    path: '/liste'
    methods: ['GET']
    controller: 'App\Domain\Maturity\Controller\SurveyController:listAction'

maturity_survey_create:
    path: '/creer'
    methods: ['GET', 'POST']
    controller: 'App\Domain\Maturity\Controller\SurveyController:createAction'

maturity_survey_edit:
    path: '/editer/{id}'
    methods: ['GET', 'POST']
    controller: 'App\Domain\Maturity\Controller\SurveyController:editAction'

maturity_survey_show:
    path: '/visualiser/{id}'
    methods: ['GET']
    controller: 'App\Domain\Maturity\Controller\SurveyController:showAction'

maturity_survey_report:
    path: '/bilan/{id}'
    methods: ['GET']
    controller: 'App\Domain\Maturity\Controller\SurveyController:reportAction'

maturity_survey_delete:
    path: '/supprimer/{id}'
    methods: ['GET']
    controller: 'App\Domain\Maturity\Controller\SurveyController:deleteAction'

maturity_survey_delete_confirm:
    path: '/supprimer/{id}/confirmation'
    methods: ['GET']
    controller: 'App\Domain\Maturity\Controller\SurveyController:deleteConfirmationAction'
