# Only store static parameters in this file

parameters:
    locale: 'fr'

    # Env variables
    # Re declared in order to use ParameterBagInterface in DI
    APP_DEFAULT_REFERENT: "%env(APP_DEFAULT_REFERENT)%"

    # DPO
    APP_DPO_ADDRESS_CITY: '%env(APP_DPO_ADDRESS_CITY)%'
    APP_DPO_ADDRESS_STREET: '%env(APP_DPO_ADDRESS_STREET)%'
    APP_DPO_ADDRESS_ZIP_CODE: '%env(APP_DPO_ADDRESS_ZIP_CODE)%'
    APP_DPO_CIVILITY: '%env(APP_DPO_CIVILITY)%'
    APP_DPO_FIRST_NAME: '%env(APP_DPO_FIRST_NAME)%'
    APP_DPO_LAST_NAME: '%env(APP_DPO_LAST_NAME)%'
    APP_DPO_COMPANY: '%env(APP_DPO_COMPANY)%'
    APP_DPO_JOB: '%env(APP_DPO_JOB)%'
    APP_DPO_MAIL: '%env(APP_DPO_MAIL)%'
    APP_DPO_PHONE_NUMBER: '%env(APP_DPO_PHONE_NUMBER)%'

    # PROVIDER & LOGO configuration
    APP_FOOTER_PROVIDER_NAME: '%env(APP_FOOTER_PROVIDER_NAME)%'
    APP_FOOTER_PROVIDER_URL: '%env(APP_FOOTER_PROVIDER_URL)%'
    APP_IMAGE_FAVICON_PATH: '%env(APP_IMAGE_FAVICON_PATH)%'
    APP_IMAGE_SIDEBAR_BOTTOM_TARGET_URL: '%env(APP_IMAGE_SIDEBAR_BOTTOM_TARGET_URL)%'
    APP_IMAGE_SIDEBAR_BOTTOM_PATH: '%env(APP_IMAGE_SIDEBAR_BOTTOM_PATH)%'
    APP_IMAGE_SIDEBAR_REDUCED_PATH: '%env(APP_IMAGE_SIDEBAR_REDUCED_PATH)%'

    #Max file upload size
    APP_MAX_UPLOAD_SIZE: '%env(APP_MAX_UPLOAD_SIZE)%'

    #Show notification icon in header
    APP_ACTIVATE_NOTIFICATIONS: '%env(APP_ACTIVATE_NOTIFICATIONS)%'

    APP_USER_DASHBOARD_ACTION_PLAN_LIMIT: '%env(APP_USER_DASHBOARD_ACTION_PLAN_LIMIT)%'

    SSO_TYPE: '%env(OAUTH_TYPE)%'
    SSO_KEY_FIELD: '%env(SSO_KEY_FIELD)%'
