services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Application\:
        resource: '../src/Application/*'
        exclude: '../src/Application/{Controller,Dictionary,Entity,Migrations,Symfony/EventSubscriber,Symfony/Form,Tests,Kernel.php}'

    App\Domain\:
        resource: '../src/Domain/*'
        exclude: '../src/Domain/*/{Cloner,Component/Mailer.php,Controller,Dictionary,Generator,Handler,Model,Symfony/EventSubscriber,Symfony/Form,Tests}'

    PhpOffice\PhpWord\PhpWord: ~
    RandomLib\Factory: ~

    App\Domain\Reporting\Metrics\UserMetric:
        arguments:
            $userLogJounalViewLimit: '%env(APP_USER_DASHBOARD_JOURNALISATION_LIMIT)%'

    Rollerworks\Component\PasswordStrength\Validator\Constraints\PasswordRequirementsValidator: ~

    App\Domain\User\Validator\Constraints\CustomPasswordValidator:
        arguments:
            $minLength: '%env(APP_PASSWORD_REQUIRE_MIN_LENGTH)%'
            $requireCaseDiff: '%env(APP_PASSWORD_REQUIRE_CASE_DIFF)%'
            $requireLetters: '%env(APP_PASSWORD_REQUIRE_LETTERS)%'
            $requireNumbers: '%env(APP_PASSWORD_REQUIRE_NUMBERS)%'
            $requireSpecialCharacter: '%env(APP_PASSWORD_REQUIRE_SPECIAL_CHARACTERS)%'

    App\Application\Symfony\OpenApi\JwtDecorator:
        decorates: 'api_platform.openapi.factory'
        autoconfigure: false

imports:
    - { resource: services/cloner.yaml }
    - { resource: services/controller.yaml }
    - { resource: services/dictionary.yaml }
    - { resource: services/event_subscriber.yaml }
    - { resource: services/generator.yaml }
    - { resource: services/mail.yaml }
