services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Application\:
        resource: '../src/Application/*'
        exclude: '../src/Application/{Controller,Dictionary,Entity,Migrations,Symfony/EventSubscriber,Symfony/Form,Tests,Kernel.php}'

    App\Domain\:
        resource: '../src/Domain/*'
        exclude: '../src/Domain/*/{Cloner,Component/Mailer.php,Controller,Dictionary,Generator,Handler,Model,Symfony/EventSubscriber,Symfony/Form,Tests}'

    PhpOffice\PhpWord\PhpWord: ~
    RandomLib\Factory: ~

    App\Domain\Reporting\Metrics\UserMetric:
        arguments:
            $userLogJounalViewLimit: '%env(APP_USER_DASHBOARD_JOURNALISATION_LIMIT)%'

imports:
    - { resource: services/cloner.yaml }
    - { resource: services/controller.yaml }
    - { resource: services/dictionary.yaml }
    - { resource: services/event_subscriber.yaml }
    - { resource: services/generator.yaml }
    - { resource: services/mail.yaml }
