parameters:
    locale: 'fr'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Application\:
        resource: '../src/Application/*'
        exclude: '../src/Application/{Controller,Entity,Migrations,Symfony/EventSubscriber,Tests,Kernel.php}'

imports:
    - { resource: services/controller.yaml }
    - { resource: services/dictionary.yaml }
    - { resource: services/event_subscriber.yaml }
