services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Infrastructure\ORM\Admin\Repository\:
        resource: '../../../../src/Infrastructure/ORM/Admin/Repository'

    App\Domain\Admin\Repository\Collectivity: '@App\Infrastructure\ORM\Admin\Repository\Collectivity'
