page_credit:
    path: /page/credit
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: Page/credit.html.twig
page_sitemap:
    path: /page/sitemap
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: Page/sitemap.html.twig
