App\Domain\Registry\Model\Embeddable\Address:
    properties:
        mail:
            - Email:
                message: 'registry_address.mail.email'
                groups: ['default']
        phoneNumber:
            - Length:
                min: 10
                max: 10
                exactMessage: 'registry_address.phone_number.length'
                groups: ['default']
            - Regex:
                pattern: '/0[1-7][0-9]{8}/'
                message: 'registry_address.phone_number.regex'
                groups: ['default']
        zipCode:
            - Length:
                min: 5
                max: 5
                exactMessage: 'registry_address.zip_code.length'
                groups: ['default']
