App\Domain\Registry\Model\ConformiteOrganisation\Evaluation:
    properties:
        conformites:
            - Valid: ~
        date:
            - NotNull:
                message: 'registry_conformite_organisation_date.date.not_null'
                groups: ['default']
            - LessThanOrEqual:
                value: today
                message: 'registry_conformite_organisation_date.date.not_posterior'
                groups: ['default']
