App\Domain\Registry\Model\Contractor:
    properties:
        contractualClausesVerified:
            - NotNull:
                message: 'registry_contractor.contractual_clauses_verified.not_null'
                groups: ['contractor']
        adoptedSecurityFeatures:
            - NotNull:
                message: 'registry_contractor.adopted_security_features.not_null'
                groups: ['contractor']
        maintainsTreatmentRegister:
            - NotNull:
                message: 'registry_contractor.maintains_treatment_register.not_null'
                groups: ['contractor']
        sendingDataOutsideEu:
            - NotNull:
                message: 'registry_contractor.sending_data_outside_eu.not_null'
                groups: ['contractor']
        name:
            - NotBlank:
                message: 'registry_contractor.name.not_blank'
                groups: ['contractor']
            - Length:
                max: 255
                groups: ['default']
        address:
            - Valid: ~
        dpo:
            - Valid: ~
        referent:
            - Length:
                max: 255
                groups: ['default']
