App\Domain\Registry\Model\Proof:
    properties:
        name:
            - NotBlank:
                message: 'registry_proof.name.not_blank'
                groups: ['default']
            - Length:
                max: 255
                groups: ['default']
        type:
            - Knp\DictionaryBundle\Validator\Constraints\Dictionary:
                name: 'registry_proof_type'
                groups: ['default']
        documentFile:
            - NotNull:
                message: 'registry_proof.document_file.not_null'
                groups: ['create']
        comment:
            - Length:
                  max: 255
                  groups: ['default']
