App\Domain\Registry\Model\Request:
    constraints:
        - App\Domain\Registry\Symfony\Validator\Constraints\RequestStateRejectionReason:
              message: 'registry_request.state_rejection_reason.mandatory'
              groups: ['default']
    properties:
        object:
            - NotBlank:
                message: 'registry_request.object.not_blank'
                groups: ['default']
            - Knp\DictionaryBundle\Validator\Constraints\Dictionary:
                name: 'registry_request_object'
                groups: ['default']
        date:
            - NotBlank:
                message: 'registry_request.date.not_blank'
                groups: ['default']
        applicant:
            - Valid: ~
        concernedPeople:
            - Valid: ~
        answer:
            - Valid: ~
        otherObject:
            - Length:
                max: 255
                groups: ['default']
        reason:
            - Length:
                max: 255
                groups: ['default']
        state:
            - Knp\DictionaryBundle\Validator\Constraints\Dictionary:
                name: 'registry_request_state'
                groups: ['default']
