App\Domain\Registry\Model\Embeddable\RequestConcernedPeople:
    properties:
        civility:
            - Knp\DictionaryBundle\Validator\Constraints\Dictionary:
                name: 'registry_request_civility'
                groups: ['default']
        phoneNumber:
            - Regex:
                pattern: '/^0[1-9][0-9]{8}$/'
                message: 'registry_request_concerned_people.phone_number.regex'
                groups: ['default']
