App\Domain\Registry\Model\Treatment:
    constraints:
        - App\Domain\Registry\Symfony\Validator\Constraints\TreatmentConcernedPeople:
              message: 'registry_treatment.concerned_people.min_count'
              groups: ['default']
    properties:
        name:
            - NotBlank:
                message: 'registry_treatment.name.not_blank'
                groups: ['default']
            - Length:
                max: 255
                groups: ['default']
        legalBasis:
            - NotBlank:
                message: 'registry_treatment.legal_basis.not_blank'
                groups: ['default']
            - Knp\DictionaryBundle\Validator\Constraints\Dictionary:
                name: 'registry_treatment_legal_basis'
                groups: ['default']
        active:
            - NotNull:
                message: 'registry_treatment.active.not_null'
                groups: ['default']
        delay:
            - Valid: ~
        manager:
            - Length:
                max: 255
                groups: ['default']
        software:
            - Length:
                max: 255
                groups: ['default']
        dataOrigin:
            - Length:
                max: 255
                groups: ['default']
        authorizedPeople:
            - Length:
                max: 255
                groups: ['default']
        securityAccessControl:
            - Valid: ~
        securityTracability:
            - Valid: ~
        securitySaving:
            - Valid: ~
        securityUpdate:
            - Valid: ~
        securityOther:
            - Valid: ~
