user_collectivity_list:
    path: '/liste'
    methods: ['GET']
    controller: 'App\Domain\User\Controller\CollectivityController:listAction'

user_collectivity_create:
    path: '/creer'
    methods: ['GET', 'POST']
    controller: 'App\Domain\User\Controller\CollectivityController:createAction'

user_collectivity_edit:
    path: '/editer/{id}'
    methods: ['GET', 'POST']
    controller: 'App\Domain\User\Controller\CollectivityController:editAction'

user_collectivity_show:
    path: '/visualiser/{id}'
    methods: ['GET']
    controller: 'App\Domain\User\Controller\CollectivityController:showAction'

user_collectivity_delete:
    path: '/supprimer/{id}'
    methods: ['GET']
    controller: 'App\Domain\User\Controller\CollectivityController:deleteAction'

user_collectivity_delete_confirm:
    path: '/supprimer/{id}/confirmation'
    methods: ['GET']
    controller: 'App\Domain\User\Controller\CollectivityController:deleteConfirmationAction'
