user_profile_collectivity_show:
    path: '/ma-collectivite/visualiser'
    methods: ['GET']
    controller: 'App\Domain\User\Controller\ProfileController:collectivityShowAction'

user_profile_collectivity_edit:
    path: '/ma-collectivite/editer'
    methods: ['GET', 'POST']
    controller: 'App\Domain\User\Controller\ProfileController:collectivityEditAction'

user_profile_user_edit:
    path: '/mon-compte/editer'
    methods: ['GET', 'POST']
    controller: 'App\Domain\User\Controller\ProfileController:userEditAction'

user_profile_get_services_content:
    path: 'mon-compte/services/{collectivityId}/{userId}'
    methods: ['GET']
    controller: 'App\Domain\User\Controller\ProfileController:getServicesContent'
