login:
    path: '/connexion'
    methods: ['GET', 'POST']
    controller: 'App\Domain\User\Controller\SecurityController:loginAction'

logout:
    path: '/deconnexion'

oauth_connect:
    path: '/oauth/connect/{service}'
    methods: [ 'GET' ]
    controller: 'App\Domain\User\Controller\SecurityController:oauthConnectAction'

oauth_check:
    path: '/oauth/check/{service}'
    methods: [ 'GET' ]
    controller: 'App\Domain\User\Controller\SecurityController:oauthCheckAction'

forget_password:
    path: '/mot-de-passe-oublie'
    methods: ['GET']
    controller: 'App\Domain\User\Controller\SecurityController:forgetPasswordAction'

forget_password_confirm:
    path: '/mot-de-passe-oublie'
    methods: ['POST']
    controller: 'App\Domain\User\Controller\SecurityController:forgetPasswordConfirmAction'

reset_password:
    path: '/reinitialisation-de-mot-de-passe/{token}'
    methods: ['GET', 'POST']
    requirements:
        token: .+
    controller: 'App\Domain\User\Controller\SecurityController:resetPasswordAction'
