user_user_list:
    path: '/liste'
    methods: ['GET']
    controller: 'App\Domain\User\Controller\UserController:listAction'

user_user_list_datatables:
    path: '/datatables'
    methods: ['POST']
    controller: 'App\Domain\User\Controller\UserController:listDataTables'

user_user_create:
    path: '/creer'
    methods: ['GET', 'POST']
    controller: 'App\Domain\User\Controller\UserController:createUser'

user_user_edit:
    path: '/editer/{id}'
    methods: ['GET', 'POST']
    controller: 'App\Domain\User\Controller\UserController:editUser'

user_user_delete:
    path: '/archiver/{id}'
    methods: ['GET']
    controller: 'App\Domain\User\Controller\UserController:deleteUser'

user_user_delete_confirm:
    path: '/archiver/{id}/confirmation'
    methods: ['GET']
    controller: 'App\Domain\User\Controller\UserController:deleteConfirmationAction'

user_user_unarchive:
    path: '/desarchiver/{id}'
    methods: ['GET']
    controller: 'App\Domain\User\Controller\UserController:unarchiveAction'

user_user_unarchive_confirm:
    path: '/desarchiver/{id}/confirmation'
    methods: ['GET']
    controller: 'App\Domain\User\Controller\UserController:unarchiveConfirmationAction'

user_user_get_services_content:
    path: '/services/{collectivityId}/{userId}'
    methods: ['GET']
    controller: 'App\Domain\User\Controller\UserController:getServicesContent'
