user_user_list:
    path: '/liste'
    methods: ['GET']
    controller: 'App\Domain\User\Controller\UserController:listAction'

user_user_create:
    path: '/creer'
    methods: ['GET', 'POST']
    controller: 'App\Domain\User\Controller\UserController:createAction'

user_user_edit:
    path: '/editer/{id}'
    methods: ['GET', 'POST']
    controller: 'App\Domain\User\Controller\UserController:editAction'

user_user_delete:
    path: '/archiver/{id}'
    methods: ['GET']
    controller: 'App\Domain\User\Controller\UserController:deleteAction'

user_user_delete_confirm:
    path: '/archiver/{id}/confirmation'
    methods: ['GET']
    controller: 'App\Domain\User\Controller\UserController:deleteConfirmationAction'

user_user_unarchive:
    path: '/desarchiver/{id}'
    methods: ['GET']
    controller: 'App\Domain\User\Controller\UserController:unarchiveAction'

user_user_unarchive_confirm:
    path: '/desarchiver/{id}/confirmation'
    methods: ['GET']
    controller: 'App\Domain\User\Controller\UserController:unarchiveConfirmationAction'
