user_user_list:
    path: '/liste'
    methods: ['GET']
    defaults:
        _controller: 'App\Domain\User\Controller\UserController:listAction'

user_user_create:
    path: '/creer'
    methods: ['GET', 'POST']
    defaults:
        _controller: 'App\Domain\User\Controller\UserController:createAction'

user_user_edit:
    path: '/editer/{id}'
    methods: ['GET', 'POST']
    defaults:
        _controller: 'App\Domain\User\Controller\UserController:editAction'

user_user_delete:
    path: '/supprimer/{id}'
    methods: ['GET']
    defaults:
        _controller: 'App\Domain\User\Controller\UserController:deleteAction'

user_user_delete_confirm:
    path: '/supprimer/{id}/confirmation'
    methods: ['GET']
    defaults:
        _controller: 'App\Domain\User\Controller\UserController:deleteConfirmationAction'
